name: Lint

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: luarocks/gh-actions-lua@master
        with:
          luaVersion: "5.4"

      - uses: luarocks/gh-actions-luarocks@master
        with:
          luaRocksVersion: "3.13.0"

      - name: dependencies
        run: |
          make dev

      - name: lint
        run: |
          make lint
